/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import gui.StartupJPanel;

/**
 *
 * @author Davidi
 */
public class ContentJFrame extends javax.swing.JFrame {

    private static ContentJFrame instance;
    /**
     * Creates new form ContentJFrame
     */
    public ContentJFrame() {
        initComponents();
        setContentPanel(new StartupJPanel());
    }

    public static ContentJFrame getInstance()
    {
        if(instance == null)
        {
            instance = new ContentJFrame();
            instance.setVisible(true);  //Make it actually pop up.  Otherwise this would run entierly in command prompt
        }
        
        return instance;
    }
    
    public void setContentPanel(JPanel p)
    {
        this.setContentPane(p);
        
        this.setSize(p.getWidth(), p.getHeight());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
